services:
  frontend:
    build:
      context: ./frontend
      target: builder
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001/api
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev

networks:
  default:
    name: twotruths-dev